-- 1.SELZIONARE TUTTI GLI STUDENTI NATI NEL 1990 
SELECT * 
FROM `students` 
WHERE `date_of_birth` BETWEEN "1990-01-01" AND "1990-12-31";

-- 2. SELZIONARE TUTTI I CORSI CHE VALGONO PIU' DI 10 CREDITI
SELECT * 
FROM `courses` 
WHERE `cfu` > 10;

-- 3. SELEZIONARE TUTTI GLI STUDENTI CHE HANNO PIU' DI 30 ANNI
SELECT * 
FROM `students`  
WHERE `date_of_birth` <= "1994-10-16";

SELECT * 
FROM `students`  
WHERE `date_of_birth` <= "1994-01-01";

-- 4. SELEZIONARE TUTTI I CORSI DEL PRIMO SEMESTRE DEL PRIMO ANNO DI UN QUALSIASI CORSO DI LAUREA
SELECT * 
FROM `courses`
WHERE `period` = "I semestre"
AND `year`= 1;

-- 5. SELEZIONARE TUTTI GLI APPELLI D'ESAME VHE AVVENGONO NEL POMERIGGIO (DOPO LE 14) DEL 20-06-2020
SELECT * 
FROM `exams` 
WHERE `hour` >= "14:00:00"
AND `date` = "2020-06-20";

-- 6. SELEZIONARE TUTTI I CORSI DI LAUREA MAGISTRALE
SELECT * 
FROM `degrees` 
WHERE `level` = "magistrale";

-- 7. DA QUANTI DIPARTIMENTI E' COMPOSTA L'UNIVERISTA'?
SELECT COUNT(`id`)
FROM `departments`;

-- 8. QUANTI SONO GLI INSEGNANTI CHE NON HANNO UN NUMERO DI TELEFONO?
SELECT * 
FROM `teachers` 
WHERE `phone`IS NULL;

-- 9. INSERIRE NELLA TABELLA DEGLI STUDENTI UN NUOVO RECORD CON I PROPRI DATI (PER IL CAMPO degree_id, INSERIRE UN VALORE CASUALE)
UPDATE `students`
SET `degree_id` = FLOOR(1 + RAND() * 50);

-- 10. CAMBIARE IL NUMERO DELL'UFFICIO DEL PROFESSOR PIETRO RIZZO IN 126
UPDATE `teachers`
SET `office_number` = 126
WHERE name = 'Pietro' AND surname = 'Rizzo';

-- 11. ELIMINARE DALLA TABELLA STUDENTI IL RECORD CREATO PRECEDENTEMENTE AL PUNTO 9
DELETE FROM `exam_student`
WHERE `student_id` = 8;

DELETE FROM `students`
WHERE `id` = 8;
